create table company (id bigint generated by default as identity, name varchar(255), primary key (id));

alter table car add constraint FKjqp14dkmi2lh5kjavv4t0dkqy foreign key (company_id) references company;