create table employee (id bigint generated by default as identity, name varchar(255), surname varchar(255), address_id bigint, department_id bigint, primary key (id));

alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department;